# Multipart
servlet:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 10MB

# AWS
cloud:
  aws:
    credentials:
      accessKey: REMOVED
      secretKey: REMOVED
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    s3:
      bucket: imnotdurnk


